<link type="text/css" rel="stylesheet" href="http://samedi.co.ke/dev/bootstrap/css/bootstrap.css" />
<link type="text/css" rel="stylesheet" href="http://samedi.co.ke/dev/bootstrap/css/bootstrap-responsive.css" />
<link href="http://samedi.co.ke/dev/slider/1/js-image-slider.css" rel="stylesheet" type="text/css" />
<link type="text/css" rel="stylesheet" href="http://samedi.co.ke/css/samedi.dev.css" />
<script src="http://samedi.co.ke/js/jquery-1.9.1.js" type="text/javascript"></script>
<script src="http://samedi.co.ke/dev/slider/1/js-image-slider.js" type="text/javascript"></script>
<script type="text/javascript" src="http://samedi.co.ke/dev/bootstrap/js/bootstrap.js" /></script>
<script src="http://samedi.co.ke/js/shop.01.js" type="text/javascript"></script>
<script src="http://samedi.co.ke/dev/bootstrap/js/bootstrap-tooltip.js" type="text/javascript"></script>
<script src="http://samedi.co.ke/js/registry.02.js" type="text/javascript"></script>
